### ISSUE TITLE
This video is not available

### ISSUE THREAD

**Issue by Erreiip** [lavalink-devs/lavaplayer#135]
Hello, i got this error in loop since more than a week, i have search on every lavaplayer repo but no one get this error.

```
10:51:59.419 [lava-daemon-pool-info-loader-2-thread-1] DEBUG com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchProvider - Attempting to parse results from search page
10:51:59.440 [lava-daemon-pool-info-loader-2-thread-1] DEBUG com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager - Loaded a playlist with identifier ytsearch:mokoko sound using YoutubeAudioSourceManager.
com.sedmelluq.discord.lavaplayer.track.BasicAudioPlaylist@39b09e92
[com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack@2a75410f, com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack@51cb6669, com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack@7d29dc33, com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack@4050890a, com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack@402dd536, com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack@4a5f1b74, com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack@79249e48, com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack@3d7840bf, com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack@1352b643, com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack@21648be6, com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack@7c6f975c, com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack@36d5dd6, com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack@50b1356, com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack@b583aa, com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack@602197, com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack@698a4fa0, com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack@34c67064, com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack@18c21d85, com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack@19afeb93, com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack@22635049]
Search results for: mokoko sound
10:51:59.441 [lava-daemon-pool-info-loader-2-thread-1] DEBUG com.sedmelluq.discord.lavaplayer.player.AudioPlayer - Firing an event with class TrackStartEvent
10:51:59.448 [lava-daemon-pool-playback-1-thread-1] DEBUG com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor - Starting to play track dmdIjOfRgKY locally with listener com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayer@4b12db65
10:51:59.452 [lava-daemon-pool-playback-1-thread-1] WARN com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker - YouTube auth tokens can't be retrieved because email and password is not set in YoutubeAudioSourceManager, age restricted videos will throw exceptions.
10:51:59.671 [JDA AudioWS-ReadThread (guildId: 1090689983305756672)] DEBUG net.dv8tion.jda.internal.audio.AudioWebSocket - Using encryption mode xsalsa20_poly1305_lite
10:51:59.750 [JDA AudioWS-ReadThread (guildId: 1090689983305756672)] DEBUG net.dv8tion.jda.internal.audio.AudioWebSocket - Unknown Audio OP code.
{"op":11,"d":{"user_ids":["373759859713114112"]}}
10:51:59.750 [JDA AudioWS-ReadThread (guildId: 1090689983305756672)] DEBUG net.dv8tion.jda.internal.audio.AudioWebSocket - Unknown Audio OP code.
{"op":18,"d":{"user_id":"373759859713114112","flags":0}}
10:51:59.751 [JDA AudioWS-ReadThread (guildId: 1090689983305756672)] DEBUG net.dv8tion.jda.internal.audio.AudioWebSocket - Unknown Audio OP code.
{"op":20,"d":{"user_id":"373759859713114112","platform":0}}
10:51:59.828 [JDA AudioWS-ReadThread (guildId: 1090689983305756672)] DEBUG net.dv8tion.jda.internal.audio.AudioWebSocket - Audio connection has finished connecting!
10:51:59.919 [JDA RateLimit-Elastic-Worker 1] DEBUG net.dv8tion.jda.internal.requests.Requester - Received response with following cf-rays: [893914e9a8c2bb69-CDG]
10:51:59.925 [JDA RateLimit-Elastic-Worker 1] DEBUG net.dv8tion.jda.api.requests.RestRateLimiter - Caching bucket hash POST/webhooks/{application_id}/{interaction_token} -> 3d2712a9e4fe17cc9d3fed4a8e672e5f
10:52:00.077 [lava-daemon-pool-playback-1-thread-1] DEBUG com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager - Parsing player script /s/player/74204f6c/player_ias.vflset/fr_FR/base.js
10:52:01.590 [lava-daemon-pool-playback-1-thread-1] DEBUG com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader - Loading track info with payload: {"context":{"thirdParty":{"embedUrl":"https://google.com"},"client":{"screenPixelDensity":1,"androidSdkVersion":30,"screenWidthPoints":1920,"clientName":"ANDROID","screenHeightPoints":1080,"screenDensityFloat":1,"clientScreen":"EMBED","clientVersion":"18.06.35"}},"racyCheckOk":true,"contentCheckOk":true,"videoId":"dmdIjOfRgKY","params":"CgIQBg","playbackContext":{"contentPlaybackContext":{"signatureTimestamp":"19886"}}}
10:52:01.591 [lava-daemon-pool-playback-1-thread-1] INFO com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker - Updating YouTube visitor id (current is null).
10:52:01.830 [lava-daemon-pool-playback-1-thread-1] INFO com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker - Updating YouTube visitor id succeeded, new one is CgtmTndTUC1MYVY3NCixibCzBjIhCgJGUhIbEhcSFQsMDg8QERITFBUWFxgZGhscHR4fICBBOgwIASCquNGJk5aBtmY%3D, next update will be after 600 seconds.
10:52:01.992 [lava-daemon-pool-playback-1-thread-1] DEBUG com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor - Common failure for playback of dmdIjOfRgKY: This video is not available
10:52:01.993 [lava-daemon-pool-playback-1-thread-1] DEBUG com.sedmelluq.discord.lavaplayer.player.AudioPlayer - Firing an event with class TrackExceptionEvent
onTrackException
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This video is not available
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:87)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:44)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:330)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1589)
10:52:01.995 [JDA AudioConnection Guild: 1090689983305756672 Sending Thread] DEBUG com.sedmelluq.discord.lavaplayer.player.AudioPlayer - Firing an event with class TrackEndEvent
rentre
NO TRACK
10:52:02.310 [JDA RateLimit-Elastic-Worker 1] DEBUG net.dv8tion.jda.internal.requests.Requester - Received response with following cf-rays: [893914f8ce1cbb69-CDG]
10:52:02.311 [JDA RateLimit-Elastic-Worker 1] DEBUG net.dv8tion.jda.api.requests.RestRateLimiter - Caching bucket hash POST/channels/{channel_id}/messages -> 3df15bae86f6647dd4dfcbd5c6949480
10:52:02.314 [JDA AudioConnection Guild: 1090689983305756672 Sending Thread] DEBUG com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor - Tried to stop track dmdIjOfRgKY which is not playing.
TimeoutSong: run: Sleeping for 10 seconds
10:52:11.107 [JDA RateLimit-Scheduler-Worker 2] DEBUG net.dv8tion.jda.api.requests.RestRateLimiter - Removed 9 expired buckets
10:52:12.828 [JDA RateLimit-Elastic-Worker 1] DEBUG net.dv8tion.jda.internal.requests.Requester - Received response with following cf-rays: [8939153a6c0ed67a-CDG]
10:52:12.828 [JDA RateLimit-Elastic-Worker 1] DEBUG net.dv8tion.jda.api.requests.RestRateLimiter - Caching bucket hash DELETE/channels/{channel_id}/messages/{message_id} -> c51d12acd501bc2e6c76ab191408bd45
10:52:12.829 [JDA RateLimit-Elastic-Worker 2] DEBUG net.dv8tion.jda.internal.requests.Requester - Received response with following cf-rays: [8939153a6c0dd67a-CDG]
10:52:12.957 [JDA Gateway-Worker 1] DEBUG net.dv8tion.jda.internal.requests.WebSocketClient - Sending voice request {"op":4,"d":{"self_deaf":false,"guild_id":"1090689983305756672","channel_id":null,"self_mute":false}}
10:52:13.068 [JDA RateLimit-Elastic-Worker 2] DEBUG net.dv8tion.jda.internal.requests.Requester - Received response with following cf-rays: [8939153c5dd2d67a-CDG]
10:52:13.068 [JDA RateLimit-Elastic-Worker 2] DEBUG net.dv8tion.jda.api.requests.RestRateLimiter - Caching bucket hash DELETE/webhooks/{webhook_id}/{token}/messages/{message_id} -> 3d2712a9e4fe17cc9d3fed4a8e672e5f
10:52:41.115 [JDA RateLimit-Scheduler-Worker 2] DEBUG net.dv8tion.jda.api.requests.RestRateLimiter - Removed 6 expired buckets
```

**Comment by devoxin** [comment]
The built-in YouTube source is deprecated. Use youtube-source instead.
