### ISSUE TITLE
'Please sign in' error in Lavaplayer

### ISSUE THREAD

**Issue by ZL927** [lavalink-devs/lavaplayer#156]
# Version info
LavaLink version: 4.0.8
LavaPlayer version: 2.2.2
youtube-plugin version: 1.8.3
lavasrc-plugin version:4.3.0
# Logs
2024-10-10T17:42:06.397+08:00  WARN 15980 --- [Lavalink] [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Suspicious exception for playback of 6dOtVTDdiauQNBQEDOtlAB

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Please sign in
        at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:102) ~[jar:file:C:\Users\user\music\.\plugins\youtube-plugin-1.8.3.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-2.2.2.jar!/:na]
        at com.github.topi314.lavasrc.mirror.MirroringAudioTrack.process(MirroringAudioTrack.java:55) ~[jar:file:C:\Users\user\music\.\plugins\lavasrc-plugin-4.3.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339) ~[lavaplayer-2.2.2.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[na:na]

**Comment by devoxin** [comment]
File an issue on the correct repository.
