### ISSUE TITLE
Links copied from YouTube Android app fail to read

### ISSUE THREAD

**Issue by aikaterna** [lavalink-devs/lavaplayer#64]
Url format used:
https://www.youtube.com/live/-RsAZYlqyK4?si=3BxDfv6_LKMi5zbQ
https://www.youtube.com/live/RRb5XV993W0?si=S9wQMrsIWOouWwTR

Traceback received:
```
2024-01-03 14:38:40.976  INFO 1798 --- [XNIO-1 task-1] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://www.youtube.com/live/-RsAZYlqyK4?si=3BxDfv6_LKMi5zbQ"
2024-01-03 14:38:41.181 ERROR 1798 --- [lava-daemon-pool-info-loader-2-thread-1] lavalink.server.player.AudioLoader       : Load failed

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Unknown file format.
	at com.sedmelluq.discord.lavaplayer.source.ProbingAudioSourceManager.handleLoadResult(ProbingAudioSourceManager.java:34) ~[lavaplayer-1.5.0.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.http.HttpAudioSourceManager.loadItem(HttpAudioSourceManager.java:81) ~[lavaplayer-1.5.0.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:428) ~[lavaplayer-1.5.0.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:410) ~[lavaplayer-1.5.0.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:208) ~[lavaplayer-1.5.0.jar!/:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]
	Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.5.0
  os.arch: aarch64
  os.name: Mac OS X
  os.version: 13.6.3
  java.vendor: Eclipse Adoptium
  java.version: 17.0.9
  java.runtime.version: 17.0.9+9
  java.vm.version: 17.0.9+9
  ```
  
Granted, the "real" url for these example tracks works fine, i.e. `https://www.youtube.com/watch?v=-RsAZYlqyK4` for the 1st example - I don't believe this url format that I'm reporting is being parsed correctly by lavaplayer.

I am using an older version of Lavalink, a v3 version, and haven't tested this on a v4 version yet.

**Comment by aikaterna** [comment]
Just found https://github.com/lavalink-devs/lavaplayer/issues/37, which seems to be resolved. Sorry for the duplicate.
