### ISSUE TITLE
I have this problem with lavaplayer

### ISSUE THREAD

**Issue by MrKaratio1337** [lavalink-devs/lavaplayer#98]
<details>
<summary>Stacktrace:</summary>

```
[19:02:11] [lava-daemon-pool-info-loader-2-thread-1/WARN]: Failure loading public suffix list from default resource
java.io.FileNotFoundException: JAR entry mozilla/public-suffix-list.txt not found in /home/crafthost_serwery/svr98059/plugins/sigma-bot-1.0-SNAPSHOT-shaded.jar
at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:143) ~[?:1.8.0_333]
at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:172) ~[?:1.8.0_333]
at java.net.URL.openStream(URL.java:1092) ~[?:1.8.0_333]
at org.apache.http.conn.util.PublicSuffixMatcherLoader.load(PublicSuffixMatcherLoader.java:61) ~[?:?]
at org.apache.http.conn.util.PublicSuffixMatcherLoader.getDefault(PublicSuffixMatcherLoader.java:89) ~[?:?]
at com.sedmelluq.discord.lavaplayer.tools.http.ExtendedHttpClientBuilder.createConnectionSocketFactory(ExtendedHttpClientBuilder.java:101) ~[?:?]
at com.sedmelluq.discord.lavaplayer.tools.http.ExtendedHttpClientBuilder.createConnectionManager(ExtendedHttpClientBuilder.java:95) ~[?:?]
at com.sedmelluq.discord.lavaplayer.tools.http.ExtendedHttpClientBuilder.build(ExtendedHttpClientBuilder.java:57) ~[?:?]
at com.sedmelluq.discord.lavaplayer.tools.io.AbstractHttpInterfaceManager.getSharedClient(AbstractHttpInterfaceManager.java:84) ~[?:?]
at com.sedmelluq.discord.lavaplayer.tools.io.ThreadLocalHttpInterfaceManager.getInterface(ThreadLocalHttpInterfaceManager.java:34) ~[?:?]
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.getHttpInterface(YoutubeAudioSourceManager.java:188) ~[?:?]
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:229) ~[?:?]
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.track(YoutubeAudioSourceManager.java:254) ~[?:?]
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.track(YoutubeAudioSourceManager.java:250) ~[?:?]
at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.routeFromUrlWithVideoId(DefaultYoutubeLinkRouter.java:103) ~[?:?]
at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.routeFromMainDomain(DefaultYoutubeLinkRouter.java:68) ~[?:?]
at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.route(DefaultYoutubeLinkRouter.java:46) ~[?:?]
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:218) ~[?:?]
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:149) ~[?:?]
at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:406) ~[?:?]
at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:388) ~[?:?]
at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:183) ~[?:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_333]
at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.executeQueue(OrderedExecutor.java:90) [sigma-bot-1.0-SNAPSHOT-shaded.jar:?]
at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.run(OrderedExecutor.java:79) [sigma-bot-1.0-SNAPSHOT-shaded.jar:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_333]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_333]
at java.lang.Thread.run(Thread.java:750) [?:1.8.0_333]
[19:02:11] [lava-daemon-pool-info-loader-2-thread-1/WARN]: Failure loading public suffix list from default resource
java.io.FileNotFoundException: JAR entry mozilla/public-suffix-list.txt not found in /home/crafthost_serwery/svr98059/plugins/sigma-bot-1.0-SNAPSHOT-shaded.jar
at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:143) ~[?:1.8.0_333]
at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:172) ~[?:1.8.0_333]
at java.net.URL.openStream(URL.java:1092) ~[?:1.8.0_333]
at org.apache.http.conn.util.PublicSuffixMatcherLoader.load(PublicSuffixMatcherLoader.java:61) ~[?:?]
at org.apache.http.conn.util.PublicSuffixMatcherLoader.getDefault(PublicSuffixMatcherLoader.java:89) ~[?:?]
at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:949) ~[?:?]
at com.sedmelluq.discord.lavaplayer.tools.http.ExtendedHttpClientBuilder.build(ExtendedHttpClientBuilder.java:58) ~[?:?]
at com.sedmelluq.discord.lavaplayer.tools.io.AbstractHttpInterfaceManager.getSharedClient(AbstractHttpInterfaceManager.java:84) ~[?:?]
at com.sedmelluq.discord.lavaplayer.tools.io.ThreadLocalHttpInterfaceManager.getInterface(ThreadLocalHttpInterfaceManager.java:34) ~[?:?]
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.getHttpInterface(YoutubeAudioSourceManager.java:188) ~[?:?]
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:229) ~[?:?]
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.track(YoutubeAudioSourceManager.java:254) ~[?:?]
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.track(YoutubeAudioSourceManager.java:250) ~[?:?]
at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.routeFromUrlWithVideoId(DefaultYoutubeLinkRouter.java:103) ~[?:?]
at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.routeFromMainDomain(DefaultYoutubeLinkRouter.java:68) ~[?:?]
at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.route(DefaultYoutubeLinkRouter.java:46) ~[?:?]
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:218) ~[?:?]
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:149) ~[?:?]
at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:406) ~[?:?]
at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:388) ~[?:?]
at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:183) ~[?:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_333]
at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.executeQueue(OrderedExecutor.java:90) [sigma-bot-1.0-SNAPSHOT-shaded.jar:?]
at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.run(OrderedExecutor.java:79) [sigma-bot-1.0-SNAPSHOT-shaded.jar:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_333]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_333]
at java.lang.Thread.run(Thread.java:750) [?:1.8.0_333]
[19:02:12] [lava-daemon-pool-playback-1-thread-1/WARN]: Exception in thread "lava-daemon-pool-playback-1-thread-1"
[19:02:12] [lava-daemon-pool-playback-1-thread-1/WARN]: java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
[19:02:12] [lava-daemon-pool-playback-1-thread-1/WARN]: at com.sedmelluq.discord.lavaplayer.container.matroska.format.MutableMatroskaBlock.getNextFrameBuffer(MutableMatroskaBlock.java:56)
[19:02:12] [lava-daemon-pool-playback-1-thread-1/WARN]: at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.processFrameInBlock(MatroskaStreamingFile.java:368)
[19:02:12] [lava-daemon-pool-playback-1-thread-1/WARN]: at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseClusterSimpleBlock(MatroskaStreamingFile.java:332)
[19:02:12] [lava-daemon-pool-playback-1-thread-1/WARN]: at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseNextCluster(MatroskaStreamingFile.java:317)
[19:02:12] [lava-daemon-pool-playback-1-thread-1/WARN]: at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.provideFrames(MatroskaStreamingFile.java:293)
[19:02:12] [lava-daemon-pool-playback-1-thread-1/WARN]: at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.lambda$process$0(MatroskaAudioTrack.java:40)
[19:02:12] [lava-daemon-pool-playback-1-thread-1/WARN]: at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:274)
[19:02:12] [lava-daemon-pool-playback-1-thread-1/WARN]: at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:247)
[19:02:12] [lava-daemon-pool-playback-1-thread-1/WARN]: at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:39)
[19:02:12] [lava-daemon-pool-playback-1-thread-1/WARN]: at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25)
[19:02:12] [lava-daemon-pool-playback-1-thread-1/WARN]: at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:83)
[19:02:12] [lava-daemon-pool-playback-1-thread-1/WARN]: at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStaticWithRetry(YoutubeAudioTrack.java:65)
[19:02:12] [lava-daemon-pool-playback-1-thread-1/WARN]: at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:52)
[19:02:12] [lava-daemon-pool-playback-1-thread-1/WARN]: at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:101)
[19:02:12] [lava-daemon-pool-playback-1-thread-1/WARN]: at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:324)
[19:02:12] [lava-daemon-pool-playback-1-thread-1/WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[19:02:12] [lava-daemon-pool-playback-1-thread-1/WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[19:02:12] [lava-daemon-pool-playback-1-thread-1/WARN]: at java.lang.Thread.run(Thread.java:750)
```
</details>

Any one know how can I fix this?

**Comment by devoxin** [comment]
I'm not sure what you're asking, could you clarify?

**Comment by devoxin** [comment]
Logs? What library are you using for managing Discord voice connections?

**Comment by devoxin** [comment]
Oh, Lavalink. Can you try [the new v4 jar](https://repo.lavalink.dev/artifacts/lavalink/99bde32d/Lavalink.jar) (or [v3 jar](https://repo.lavalink.dev/artifacts/lavalink/4acd52cb/Lavalink.jar) if you're a Lavalink v3 user) and report back?

**Comment by devoxin** [comment]
Closing as stale.
